
name: DockerHub Nightly

on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push nightly Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: mattpolzin2/idris-docker:nightly
          target: idris-nightly
          file: Dockerfile.ubuntu
      - name: Build and push Idv Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: mattpolzin2/idris-docker:idv
          target: idris-idv
          file: Dockerfile.ubuntu
      - name: Build and push Katla Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: mattpolzin2/idris-docker:nightly-katla
          target: katla
          file: Dockerfile.ubuntu.katla

